import AppConfigs from '../config/env';

export default {
  LOGIN: AppConfigs.API_ENDPOINT + 'auth/login',
  LOG_OUT: AppConfigs.API_ENDPOINT + 'auth/logout',
  REGISTER_ID: AppConfigs.API_ENDPOINT + 'auth/register_id',
  RESET_PASSWORD: AppConfigs.API_ENDPOINT + 'auth/reset_password',
  CONFIRM_RESET_PASSWORD:
    AppConfigs.API_ENDPOINT + 'auth/confirm_reset_password',
  UPDATE_EMAIL: AppConfigs.API_ENDPOINT + 'auth/update_email',
  VERIFY_EMAIL: AppConfigs.API_ENDPOINT + 'auth/verify_email',
  RESEND_EMAIL_CODE: AppConfigs.API_ENDPOINT + 'auth/resend_verify_email',
  UPDATE_PHONE: AppConfigs.API_ENDPOINT + 'auth/update_phone',
  UPDATE_PASSWORD: AppConfigs.API_ENDPOINT + 'auth/update_password',
  UPLOAD_AVATAR: AppConfigs.API_ENDPOINT + 'auth/upload',
  DONVI_PHONGBAN_NV: AppConfigs.API_ENDPOINT + 'dv_pb/nghiep_vu/list',
  DONVI_PHONGBAN_SX: AppConfigs.API_ENDPOINT + 'dv_pb/sanxuat',
  DOC_VBNB_LIST: AppConfigs.API_ENDPOINT + 'document/vbnb/list',
  DOC_VBNB_DETAIL: AppConfigs.API_ENDPOINT + 'document/vbnb/{id}',
  DOC_VBNB_FILE: AppConfigs.API_ENDPOINT + 'document/vbnb/{id}/file',
  DOC_FILE_VBNB: AppConfigs.API_ENDPOINT + 'document/vbnb/file/{id}',
  DOC_VBDEN_LIST: AppConfigs.API_ENDPOINT + 'document/vbden/list',
  DOC_VBDEN_DETAIL: AppConfigs.API_ENDPOINT + 'document/vbden/{id}',
  SALARY_LIST: AppConfigs.API_ENDPOINT + 'salary/list',
  SALARY_DETAIL: AppConfigs.API_ENDPOINT + 'salary/detail',
  CBC_DV_PB: AppConfigs.API_CBC + 'nangsuat/donvi_phongban',
  CBC_MA_HANG: AppConfigs.API_CBC + 'cbc/mahang?phongban={id}',
  CBC_DATA: AppConfigs.API_CBC + 'cbc/nangsuat',
  NEWS_LIST: AppConfigs.API_ENDPOINT + 'news/list',
  NEWS_DETAIL: AppConfigs.API_ENDPOINT + 'news/{id}',
  NEWS_SET_RATE: AppConfigs.API_ENDPOINT + 'news/{id}/rate',
  NEWS_COMMENTS: AppConfigs.API_ENDPOINT + 'news/{id}/comments',
  NEWS_CHILD_COMMENTS: AppConfigs.API_ENDPOINT + 'news/comments/{id}/child',
  NEWS_DELETE_COMMENT: AppConfigs.API_ENDPOINT + 'news/comments/{id}/delete',
  NEWS_ACCEPT_COMMENT: AppConfigs.API_ENDPOINT + 'news/comments/{id}/accept',
  NEWS_PENDING_COMMENTS: AppConfigs.API_ENDPOINT + 'news/comments/pending',
};
