const AppLang = {
  common: {
    defaultTitleModal: 'Thông báo',
    defaultErrorTitle: 'Error!',
    defaultSuccessTitle: 'Success!',
    emptyList: 'Không có dữ liệu',
    required: 'Bắt buộc',
    functionUpdating:
      'Chức năng đang được nâng cấp.\nXin lỗi vì sự bất tiện này',
    errors: {
      somethingWentWrong: 'Có lỗi xảy ra.\nVui lòng kiểm tra lại',
      thisIsRequired: 'Thông tin bắt buộc',
      allFieldsRequired: 'Vui lòng nhập tất cả thông tin',
      allFieldMarkRequired: 'Vui lòng nhập các thông tin bắt buộc',
    },
    logout: {
      title: 'Đăng xuất',
      body: 'Bạn có muốn đăng xuất?',
    },
    update: {
      title: 'CẬP NHẬT',
      body: 'Đã có bản cập nhật mới.',
    },
    buttonSave: 'Lưu',
    buttonUpdate: 'Cập nhật',
    buttonCancel: 'Huỷ',
    buttonDelete: 'Xoá',
  },
  screens: {
    auth: {
      loginTitle: 'Đăng nhập',
      forgotTitle: 'Quên mật khẩu',
      resetTitle: 'Tạo mật khẩu mới',
      mans: 'Mã nhân sự',
      confirmCode: 'Mã xác minh',
      taikhoanHCVP: 'Tài khoản hành chính văn phòng',
      password: 'Mật khẩu',
      confirmPassword: 'Xác nhận mật khẩu',
      buttons: {
        login: 'Đăng nhập',
        forgotPassword: 'Quên mật khẩu?',
        resetPassword: 'Tạo lại mật khẩu',
        updatePassword: 'Cập nhật mật khẩu',
        accept: 'Xác nhận',
        resend: 'Gửi lại mã xác minh',
      },
      errors: {
        loginError:
          'Đăng nhập không thành công.\nNếu bạn quên mật khẩu. Chọn Quên mật khẩu',
        emptyUsername: 'Chưa nhập tài khoản/mã nhân sự',
        invalidCode: 'Mã xác minh không đúng',
        shortPassword: 'Mật khẩu phải ít nhất 6 ký tự',
        passwordNotMatch: 'Xác minh mật khẩu không đúng',
      },
      resetNote:
        'Kiểm tra mã xác minh trong Hộp thư đến hoặc mục Thư rác trong email bạn đã xác minh.',
      messages: {
        resent:
          'Đã gửi mã xác minh.\nVui lòng kiểm tra email để lấy mã xác minh',
        resetSuccess: 'Tạo mật khẩu mới thành công',
      },
    },
    welcome: {
      functions: {
        document: 'Văn bản',
        news: 'Bảng tin',
        feedback: 'Phản ánh ý kiến',
        cbc: 'Theo dõi CBC',
        salary: 'Tra cứu lương',
        salaryDetails: 'Chi tiết lương',
        report: 'Báo cáo',
        calendar: 'Lịch công việc',
        todo: 'Giao nhận việc',
      },
      profilePage: 'Thông tin cá nhân',
      uploadAvatarSuccess: 'Cập nhật ảnh đại diện thành công',
    },
    email: {
      title: 'Cập nhật email',
      email: 'Địa chỉ email',
      code: 'Mã xác minh',
      buttons: {
        update: 'Cập nhật',
        verify: 'Xác minh',
        resend: 'Gửi lại mã xác minh',
      },
      errors: {
        emptyEmail: 'Chưa nhập địa chỉ email',
        invalidEmail: 'Địa chỉ email không hợp lệ',
        invalidCode: 'Mã xác minh không đúng',
      },
      messages: {
        updated:
          'Cập nhật email thành công.\nVui lòng kiểm tra email và nhập mã xác minh để hoàn tất',
        resent:
          'Đã gửi mã xác minh.\nVui lòng kiểm tra email và nhập mã xác minh để hoàn tất',
        verified: 'Xác minh địa chỉ email thành công.',
      },
    },
    news: {
      empty: 'Không có bản tin nào',
      detailTitle: 'Chi tiết bản tin',
      enterMessage: 'Nhập bình luận',
      replying: 'Đang trả lời',
      waitingAccept: 'Chờ duyệt',
    },
    calendar: {
      details: 'Chi tiết công việc',
      pickDate: 'Chọn ngày',
      pickTime: 'Chọn thời gian',
      batDau: 'Thời gian bắt đầu',
      ketThuc: 'Thời gian kết thúc',
      tenViec: 'Tên công việc',
      diaChi: 'Địa chỉ',
      ghiChu: 'Ghi chú',
      hoanThanh: 'Hoàn thành',
      thongBao: 'Thông báo',
      lapLai: 'Lặp lại',
      ketThucLapLai: 'Kết thúc lặp lại',
      delete: {
        title: 'Xoá lịch',
        message: 'Bạn có chắc chắn muốn xoá lịch này',
      },
      alerts: {
        none: 'Không',
        atTime: 'Đúng giờ',
        before5min: 'Trước 5 phút',
        before10min: 'Trước 10 phút',
        before15min: 'Trước 15 phút',
        before30min: 'Trước 30 phút',
        before1hour: 'Trước 1 giờ',
        before1day: 'Trước 1 ngày',
      },
      loops: {
        none: 'Không',
        everyDays: 'Hàng ngày',
        everyWeeks: 'Hàng tuần',
        everyMonths: 'Hàng tháng',
        everyYears: 'Hàng năm',
      },
      times: {
        minutes1: '1 phút',
        minutes5: '5 phút',
        minutes15: '15 phút',
        minutes30: '30 phút',
        minutes60: '60 phút',
        minutes120: '120 phút',
        morning: 'Sáng',
        afernoon: 'Chiều',
        allDay: 'Cả ngày',
        hours1: '1 giờ',
        hours2: '2 giờ',
        hours4: '4 giờ',
        hours8: '8 giờ',
      },
      buttons: {
        save: 'Lưu',
        update: 'Cập nhật',
        delete: 'Xoá',
      },
      errors: {
        emptyTitleAddress: 'Chưa nhập tiêu đề và địa chỉ công việc',
        invalidEndTime: 'Thời gian kết thúc không hợp lệ',
        invalidEndLoopTime: 'Thời gian kết thúc lặp lại phải lớn hơn hiện tại',
      },
      messages: {
        saved: 'Tạo công việc thành công',
        updated: 'Cập nhật công việc thành công',
        deleted: 'Đã xoá công việc',
      },
      filter: {
        title1: 'Bộ lọc',
        title2: 'Hiển thị',
        time: 'Thời gian',
        timeRange: 'Khoảng thời gian',
        donvi: 'Đơn vị',
        apply: 'Áp dụng',
        onlyMe: 'Chỉ hiển thị lịch của cá nhân',
        groupByDay: 'Nhóm theo ngày',
        groupByUser: 'Nhóm theo cá nhân',
        nonGroup: 'Không nhóm',
        all: 'Tất cả',
      },
    },
    menu: {
      title: 'Menu',
      functions: {
        report: 'Báo cáo',
        qltbi: 'Quản lý thiết bị',
        news: 'Bảng tin',
        rate: 'Đánh giá ứng dụng',
      },
    },
    profile: {
      title: 'Thông tin cá nhân',
      updatePhone: 'Cập nhật số điện thoại',
      updatePassword: 'Cập nhật mật khẩu',
      hoTen: 'Họ tên',
      maNS: 'Mã nhân sự',
      soCMT: 'Số CMND',
      ngaySinh: 'Ngày sinh',
      chucVu: 'Chức vụ',
      donVi: 'Đơn vị',
      phoneNumber: 'Số điện thoại',
      email: 'Email',
      newPassword: 'Mật khẩu mới',
      password: 'Mật khẩu',
      confirmPassword: 'Xác nhận mật khẩu mới',
      verify: 'Xác thực',
      errors: {
        emptyPhone: 'Chưa nhập số điện thoại',
        invalidPhone: 'Số điện thoại không hợp lệ',
        shortPassword: 'Mật khẩu phải ít nhất 6 ký tự',
        passwordNotMatch: 'Xác minh mật khẩu không đúng',
      },
      messages: {
        updatePhoneSuccess: 'Cập nhật số điện thoại thành công',
        updatePasswordSuccess: 'Cập nhật mật khẩu thành công',
      },
    },
    document: {
      title: 'Văn bản',
      details: 'Chi tiết văn bản',
      emptyList: 'Không có văn bản',
      placeholderSearch: 'Tìm số văn bản, trích yếu...',
    },
    documentDetails: {
      soCongVan: 'Số công văn',
      ngayCongVan: 'Ngày công văn',
      loaiVanBan: 'Loại văn bản',
      nhomVanBan: 'Nhóm văn bản',
      noiBanHanh: 'Nơi ban hành',
      nguoiChuTri: 'Người chủ trì',
      doKhan: 'Độ khẩn',
      trichYeu: 'Trích yếu',
      taiLieu: 'Tài liệu',
    },
    todo: {
      list: 'Giao nhận việc',
      listAssigned: 'Được giao',
      listDelivered: 'Đã giao',
      noAssigned: 'Không có công việc nào được giao',
      noDelivered: 'Chưa giao công việc nào',
      details: 'Chi tiết công việc',
      nguoiGiao: 'Người giao việc',
      nguoiThucHien: 'Người thực hiện',
      userModal: 'Chọn người thực hiện',
      ngayGiaoViec: 'Ngày giao việc',
      ngayHoanThanh: 'Ngày hoàn thành',
      thoiGianBatDau: 'Thời gian bắt đầu',
      thoiGianKetThuc: 'Thời gian kết thúc',
      thoiGianHoanThanh: 'Hoàn thành thực tế',
      timePerDay: 'Thời gian làm/ngày',
      tinhTrang: 'Tình trạng',
      maHang: 'Mã hàng',
      nhapMaHang: 'Nhập mã hàng',
      loaiCongViec: 'Loại công việc',
      checklist: 'Checklist',
      documents: 'Tài liệu',
      addChecklist: 'Thêm công việc',
      addListFile: 'Thêm file',
      comments: 'Trao đổi',
      addComment: 'Nhập nội dung trao đổi',
      findUser: 'Tìm người, chi nhánh, chức vụ...',
      errors: {
        emptyTitle: 'Chưa nhập tên công việc',
        invalidEndTime: 'Phải sau thời gian bắt đầu',
        changeUserDoing: 'Chỉ người giao việc mới được thay đổi',
      },
      askDelete: {
        title: 'Xoá công việc',
        message: 'Bạn có chắc chắn muốn xoá công việc này',
      },
      deleteFile: {
        title: 'Xoá tài liệu',
        message: 'Bạn có chắc chắn muốn xoá tài liệu này',
      },
      buttons: {
        doing: 'Đang làm',
        pause: 'Vướng mắc',
        done: 'Hoàn thành',
        expired: 'Quá hạn',
      },
      messages: {
        saved: 'Lưu công việc thành công',
        update: 'Cập nhật công việc thành công',
        deleted: 'Đã xoá',
      },
      includeDone: 'Hiển thị cả việc hoàn thành',
    },
    report: {
      sxkd: {
        title: 'Báo cáo sản xuất kinh doanh',
      },
      sanxuat: 'Báo cáo sản xuất',
      kinhdoanh: 'Báo cáo kinh doanh',
      cbc: 'Cân bằng chuyền',
    },
    salary: {
      details: 'Chi tiết bảng lương',
      exportPDF: 'Mở file PDF',
      notAllowAccessStorage: 'Ứng dụng cần truy cập bộ nhớ để tải bảng lương',
    },
  },
};

export default AppLang;
